version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-updates:
        patterns:
          - "*"
        update-types:
          - "all"

