version: '3.8'

services:
  app:
    build: ./app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/kcff-matc-hub_development
      - RAILS_ENV=development
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kcff-match-hub_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
