version: '3.8'

services:
  app:
    build: ./app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .app-env
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    env_file:
      - .db-env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
