version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: environments/development/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    env_file:
      - environments/development/.app-env
    depends_on:
      - db
  db:
    image: postgres:16.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - environments/development/.db-env

volumes:
  pgdata:
