require:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/LineLength:
  Exclude:
    - 'app/helpers/form_builder/admin_form_builder.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20240217131001_create_active_storage_tables.active_storage.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20240217131001_create_active_storage_tables.active_storage.rb'

Metrics/ParameterLists:
  Exclude:
    - 'app/helpers/form_builder/admin_form_builder.rb'


Rails/NotNullColumn:
  Exclude:
    - db/migrate/20240505034131_add_season_id_to_game_schedules.rb

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false
