require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20240217131001_create_active_storage_tables.active_storage.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20240217131001_create_active_storage_tables.active_storage.rb'

Style/Documentation:
  Enabled: false
