# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

gem 'aws-sdk-s3', require: false
gem 'bootsnap', require: false
gem 'haml-rails'
gem 'importmap-rails'
gem 'jbuilder'
gem 'kaminari'
gem 'omniauth-google-oauth2'
gem 'omniauth-rails_csrf_protection'
gem 'pg'
gem 'propshaft'
gem 'puma'
gem 'rails'
gem 'stimulus-rails'
gem 'turbo-rails'
gem 'tzinfo-data'

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'haml_lint', require: false
  gem 'rspec-rails', require: false
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end
