# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

gem 'bootsnap', require: false
gem 'importmap-rails'
gem 'jbuilder'
gem 'pg'
gem 'propshaft'
gem 'puma'
gem 'rails'
gem 'rubocop', require: false
gem 'rubocop-rails', require: false
gem 'stimulus-rails'
gem 'turbo-rails'
gem 'tzinfo-data'

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
end
