name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: ./app
        bundler-cache: true

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Run Haml-Lint
      run: bundle exec haml-lint app/**/*.html.haml
