name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kcff_match_hub_test
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_HOST: localhost
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: kcff_match_hub_test
      GOOGLE_CLIENT_ID: your-dummy-client-id.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: your-dummy-client-secret

    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: ./app
        bundler-cache: true

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Run Haml-Lint
      run: bundle exec haml-lint app/**/*.html.haml

    - name: Set up Database
      run: bundle exec rake db:schema:load

    - name: Run RSpec
      run: bundle exec rspec
